sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - mongodb
  - redis-server

env:
  global:
    - TESTS_ZEND_CACHE_XCACHE_ENABLED=true

matrix:
  fast_finish: true
  include:
    - php: 5.5

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - wget http://xcache.lighttpd.net/pub/Releases/3.2.0/xcache-3.2.0.tar.gz && tar -zxvf xcache-3.2.0.tar.gz
  - (cd xcache-3.2.0 && phpize && ./configure --enable-xcache --enable-xcache-coverager)

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  - echo "yes\nno\n" | pecl -d preferred_state=beta install apcu
  - (cd xcache-3.2.0 && make && make install)

before_script:
  - phpenv config-add .ci/php.ini || return 0

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
